repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: debug-statements
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
        - id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    - id: flake8
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.3
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [-l, --recursive, -x, tests]
        files: .py$
-   repo: local
    hooks:
    -   id: tests
        name: run tests
        entry: pytest -v
        language: system
        types: [python]
        stages: [push]
